### ISSUE TITLE
Recommend J-Link Conifigurator over Zadig to install generic WinUSB driver

### ISSUE THREAD

**Issue by aloebs29** [probe-rs/webpage#117]
The documentation recommends Zadig to install a generic WinUSB driver for J-Link devices on Windows:
https://probe.rs/docs/getting-started/probe-setup/#windows-1

In my opinion, the J-Link Configurator should be the preferred tool since it is published by Segger and supports this functionality (it is also pretty easy to make mistakes with Zadig). In addition, J-Link Configurator is probably the easiest tool to use to restore the J-Link USB driver, should someone need to do so in the future.

This is the home page for the tool itself: https://www.segger.com/products/debug-probes/j-link/tools/j-link-configurator/
And a wiki article showing how to configure a probe to use WinUSB: https://wiki.segger.com/J-Link_on_Windows_ARM

**Comment by bugadani** [comment]
We're happy to take contributions if you'd like to write up instructions. Unfortunately, my device isn't supported in J-Link Configurator so I can't test if the would-be installed driver actually works.

![image](https://github.com/probe-rs/webpage/assets/977627/903399a2-50e1-4f61-b396-aa138f914c08)

**Comment by aloebs29** [comment]
Sorry for the belated response -- I'll write up some instructions for this with a note that the method isn't supported on all probes (and leave the link for Zadig as an additional method).

I tried plugging in a Nordic dev kit that has a J-Link OB Debugger and the option for setting the driver as WinUSB in JLink Configurator was greyed out for me also (it does work for my JLink Compact Plus however).
