### ISSUE TITLE
Current documentation to `cargo install probe-rs-tools` fails due to #2613

### ISSUE THREAD

**Issue by xobs** [probe-rs/webpage#149]
**Describe the bug**
The documentation at https://probe.rs/docs/getting-started/installation/#installation says to install from source, run `cargo install probe-rs-tools`. However, this fails due to probe-rs/probe-rs#2613.

Since this issue is closed, a new release should be made with the fix in place, or the documentation should be updated to remove the suggestion to run `cargo install probe-rs-tools`, or it should add `--locked` to the normal release.

**To Reproduce**

1. Run `cargo install probe-rs-tools` or `cargo install probe-rs-tools --force`

**Expected behavior**
The software should install.

**Desktop (please complete the following information):**

- macOS Mojave

**Additional context**
The command `cargo install probe-rs-tools --force --locked` works. Omitting `--locked` causes the failure, but the documentation only says to include `--locked` when building the nightly version.

**Comment by brainstorm** [comment]
Install from source in the docs still mentions that "No additional setup is required.":

https://probe.rs/docs/getting-started/installation/#macos

So folks like me will try what xobs did and fail for a while until `cargo binstall` or other "unusual" ways 🤷‍♂

**Comment by Tiwalun** [comment]
> Install from source in the docs still mentions that "No additional setup is required.":
> 
> https://probe.rs/docs/getting-started/installation/#macos
> 
> So folks like me will try what xobs did and fail for a while until `cargo binstall` or other "unusual" ways 🤷‍♂

The documentation says that you should run `cargo install --locked`. No additional setups means that no other packages have to be installed. 

This is a fundamental issue with `cargo install`, we can't solve this. You need to pass `--locked`.
