### ISSUE TITLE
Webpage suggests `--list-targets` which is not available

### ISSUE THREAD

**Issue by jounathaen** [probe-rs/webpage#6]
The webpage suggests the following:
```bash
# Don't know if your target is available
# and what it's name is?
cargo flash --list-targets
```

However, cargo flash does not know `--list-targets` (At least not v.0.8.0) but `--list-probes`.

**Comment by Yatekii** [comment]
This is already fixed but not deployed. Sorry for the inconvenience! I will have time after my oxidize talk to fix all this :)

**Comment by jounathaen** [comment]
Was no inconvenience. Just a minor detail I noticed. Looking forward to the talk!

**Comment by Yatekii** [comment]
This fix is deployed :) Thanks again!
